CREATE TABLE IF NOT EXISTS topicos (
    id BIGINT NOT NULL AUTO_INCREMENT,
    titulo VARCHAR(100) NOT NULL,
    mensaje VARCHAR(100) NOT NULL,
    nombreCurso VARCHAR(100) NOT NULL,
    autor VARCHAR(100) NOT NULL,
    fechaCreacion DATETIME NOT NULL,
    status ENUM('ACTIVO', 'INACTIVO', 'ARCHIVADO') NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS usuarios (
    id BIGINT NOT NULL AUTO_INCREMENT,
    login VARCHAR(100) NOT NULL,
    clave VARCHAR(300) NOT NULL,
    PRIMARY KEY (id)
);

